on:
  push:
    branches:
      - main

env:
  APP_NAME: cord

jobs:
  CI/CD:
    runs-on: self-hosted
    steps:
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.10.1
          cabal-version: 3.12.1.0
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build and Deploy
        run: |
          cabal update
          cabal build
          cabal install exe:$APP_NAME --install-method=copy --overwrite-policy=always --installdir=/apps/$APP_NAME
          # cabal run
          # pkill -f myapp || true
          # nohup /path/to/deploy/myapp &
