on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          cabal update
          cabal build
          cabal install exe:cord --install-method=copy --overwrite-policy=always --installdir=$HOME/deploy/bin/cord
          pkill -f $HOME/deploy/bin/cord/cord || true
          RUNNER_TRACKING_ID="" && nohup $HOME/deploy/bin/cord/cord > cord.log &
