on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build and Deploy
        run: |
          cabal update
          cabal build
          cabal install exe:cord --install-method=copy --overwrite-policy=always --installdir=~/deploy/bin
          # cabal run
          # pkill -f myapp || true
          # nohup /path/to/deploy/myapp &
