on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
          # - name: Setup Haskell
          #   uses: haskell-actions/setup@v2
          #   with:
          #     ghc-version: 9.10.1
          #     cabal-version: 3.12.1.0
      - name: Build and Deploy
        run: |
          cabal update
          cabal build
          cabal install exe:cord --install-method=copy --overwrite-policy=always --installdir=/apps/cord
          # cabal run
          # pkill -f myapp || true
          # nohup /path/to/deploy/myapp &
